### ISSUE TITLE
Feature Request: Convert Between Anything to another Unit

### ISSUE THREAD

**Issue by avipars** [Digidemic/UnitOf#2]
Hello, 

I was playing around with your library and found it really useful. I am working on a small application and got stuck in a place where I want to add a "missing conversion" to an existing UnitOf object. I am aware that it is possible to just create a unit in the Anything class but how would I be able to convert it to an existing unit. For example, I want to add 100 Liters per Kilometer to the FuelEconomy object. it would be great if I would be able to have it convert to MPG or KPL. Is this possible and am I missing something? If not, is there a solution to this issue that I am facing? 

Thank you very much!

**Comment by Digidemic** [comment]
Hi!
So sorry for the delay. Thank you for the kind words and detailed question! From reading your issue, it sounds like you really understand UnitOf and its concepts (which is super flattering)! I am guessing you are using UnitOf for Java (seeing you have a conversion app of your own on Google Play, nice work).

The issue with "Liter per 100 km" specifically is its conversion factor in relation to "Kilometer per Liter" (the key being used for UnitOf.FuelEconomy) is not converted by a constant value, rather a small equation. The UnitOf.FuelEconomy enum is not structured to use equations like how UnitOf.Temperature or UnitOf.NumericBase work. Because of that, adding in this unit with the current structure does not seem possible and would require a rewrite of the entire UnitOf.FuelEconomy class. If the conversion factor was a constant then you would just need to add your new key/value to the UnitOf.FuelEconomy enum with the constant name of your choosing and the conversion factor.

There is a solution for "Liter per 100 km", but may not be the prettiest. You can use 100 as a constant that divides by your "L / 100 km" value which is then passed into "fromKilometersPerLiter".
Here is an example (in Java) if you are looking to convert 5 Liters per 100 km into Miles Per Gallon (US):


`int val= 5;`
`UnitOf.FuelEconomy foo =new UnitOf.FuelEconomy().fromKilometersPerLiter(100 /val);`
`foo.toMilesPerGallonUS();`


This formula could be added into UnitOf.FuelEconomy's "From" and "To" methods without creating a new key/value, but would make the super method "getValuePassed" invalid as a conversion needs to be applied to the initial value passed.

Does that answer your question?

Regardless, if you have any other questions, concerns, or suggestions please let me know!
Thank you

-Adam

**Comment by avipars** [comment]
Thank you for the detailed answer.
 I started my app as a side project and was manually setting the conversion values for each input. There was a lot of user error (my fault) and rounding issues. I went searching for a better answer and your library was the key! Thank you again, and good luck.

**Comment by Digidemic** [comment]
Happy to hear and thank you!
Is it okay if I close this issue then?

**Comment by avipars** [comment]
Of course.
